### ISSUE TITLE
QuickApp crashed

### ISSUE THREAD

**Issue by Happyhc2** [GitHub4Eddy/tibber_live#1]
I am running both Tibber Monitor and Tibber Live. Great code! Many thanks!

Tibber Live has never worked the whole way. I get this info. My Fibaro is live on the web. What is failing?
[30.08.2022] [09:25:00] [ERROR] [QUICKAPP87]: QuickApp crashed
[30.08.2022] [09:25:00] [ERROR] [QUICKAPP87]: Unknown error occurred: void connect(WebSocketClientTls&,std::string const&)

The timestamp is struck at 16-06-2022 16:43:20.

I have entered my personal token and my home id.

**Comment by Happyhc2** [comment]
I have now increased the debug level to 3 and then I get, if it helps:

[01.09.2022] [22:19:01] [DEBUG] [TIBBER LIVE ID:103]: onInit
[01.09.2022] [22:19:01] [DEBUG] [TIBBER LIVE ID:103]: getData
[01.09.2022] [22:19:01] [DEBUG] [TIBBER LIVE ID:103]: Connect: wss://api.tibber.com/v1-beta/gql/subscriptions {"Sec-WebSocket-Protocol":"graphql-ws","Authorization":"*****MY TOKEN WAS HERE*****"}
[01.09.2022] [22:19:01] [ERROR] [QUICKAPP103]: QuickApp crashed
[01.09.2022] [22:19:01] [ERROR] [QUICKAPP103]: Unknown error occurred: void connect(WebSocketClientTls&,std::string const&)

**Comment by GitHub4Eddy** [comment]
You could test it in the Tibber Explorer: https://developer.tibber.com/explorer

If the “real time subscription” works overthere, it should work in the quickapp.

**Comment by Happyhc2** [comment]
Dear Eddy,

 

Yes, it very odd. I have tried running the Tibber Live script in the explorer and I get this answer:

 

{

  "liveMeasurement": {

    "power": 61,

    "maxPower": 898,

    "powerProduction": 0,

    "maxPowerProduction": 0,

    "accumulatedConsumption": 2.579,

    "accumulatedProduction": 0,

    "accumulatedCost": 11.037566,

    "currency": "SEK",

    "lastMeterConsumption": 2471.043,

    "lastMeterProduction": 0.005,

    "voltagePhase1": 237.4,

    "voltagePhase2": 239.1,

    "voltagePhase3": 238.5,

    "currentL1": 0,

    "currentL2": 0.4,

    "currentL3": 0,

    "accumulatedConsumptionLastHour": 0.013,

    "accumulatedProductionLastHour": 0,

    "accumulatedReward": null,

    "minPower": 26,

    "averagePower": 127.6,

    "powerReactive": 0,

    "powerProductionReactive": 52,

    "minPowerProduction": 0,

    "powerFactor": 0.761,

    "signalStrength": -24,

    "timestamp": "2022-09-02T20:12:59.000+02:00"

  }

}

 

That means that the token and house id works. The data seems to correspond to my Tibber app data. From the debug info, it seems to crash upon connection:

 

[02.09.2022] [20:17:18] [DEBUG] [TIBBER LIVE ID:103]: Connect: wss://api.tibber.com/v1-beta/gql/subscriptions {"Sec-WebSocket-Protocol":"graphql-ws","Authorization":"TOKEN"}

[02.09.2022] [20:17:18] [ERROR] [QUICKAPP103]: QuickApp crashed

[02.09.2022] [20:17:18] [ERROR] [QUICKAPP103]: Unknown error occurred: void connect(WebSocketClientTls&,std::string const&)

 

Very weird… 

 

Håkan

 

Från: GitHub4Eddy ***@***.***> 
Skickat: den 2 september 2022 19:43
Till: GitHub4Eddy/tibber_live ***@***.***>
Kopia: Happyhc2 ***@***.***>; Author ***@***.***>
Ämne: Re: [GitHub4Eddy/tibber_live] QuickApp crashed (Issue #1)

 

You could test it in the Tibber Explorer: https://developer.tibber.com/explorer

If the “real time subscription” works overthere, it should work in the quickapp.

**Comment by GitHub4Eddy** [comment]
Strange.

Do you run the beta firmware?

**Comment by Happyhc2** [comment]
If you want I can send my token and homeid to exclude that it is a Tibber problem.Skickat från min Galaxy
-------- Originalmeddelande --------Från: GitHub4Eddy ***@***.***> Datum: 2022-09-02  22:45  (GMT+01:00) Till: GitHub4Eddy/tibber_live ***@***.***> Kopia: Happyhc2 ***@***.***>, Author ***@***.***> Ämne: Re: [GitHub4Eddy/tibber_live] QuickApp crashed (Issue #1) 
Strange.
Do you run the beta firmware?

**Comment by GitHub4Eddy** [comment]
Do you run the beta firmware? (You need to)

**Comment by Happyhc2** [comment]
Oh! I did not know. I will update as soon as I get there and retry. What has been added that the app uses?HåkanSkickat från min Galaxy
-------- Originalmeddelande --------Från: GitHub4Eddy ***@***.***> Datum: 2022-09-03  16:57  (GMT+01:00) Till: GitHub4Eddy/tibber_live ***@***.***> Kopia: Happyhc2 ***@***.***>, Author ***@***.***> Ämne: Re: [GitHub4Eddy/tibber_live] QuickApp crashed (Issue #1) 
Do you run the beta firmware? (You need to)

**Comment by GitHub4Eddy** [comment]
Yes, the webSocket has some changes in the beta formware. Be careful with the beta version, some other things wonkt work and new issues can be introduced. (I don’t run the beta)

**Comment by Happyhc2** [comment]
No, I am running 5.070.57 at the moment.Skickat från min Galaxy
-------- Originalmeddelande --------Från: GitHub4Eddy ***@***.***> Datum: 2022-09-02  22:45  (GMT+01:00) Till: GitHub4Eddy/tibber_live ***@***.***> Kopia: Happyhc2 ***@***.***>, Author ***@***.***> Ämne: Re: [GitHub4Eddy/tibber_live] QuickApp crashed (Issue #1) 
Strange.
Do you run the beta firmware?

**Comment by GitHub4Eddy** [comment]
It won’t work with firmware 5070.47. You need to update the firmware. You can use the stable firmware version 5120.

**Comment by Happyhc2** [comment]
Dear Eddy,

I am really sorry to bother you, but I have one question. My Fibaro home center 3 can not handle the global variable for CHEAP, VERY CHEAP etc. In the scene editor, I pull up a block under panel/variables, but the Choose button is not accessible.

I am in need of using the variables in a scene. Is there a way to access the variable also as a local variable in Tibber monitor? It would be very useful.

All the best,
Håkan

**Comment by GitHub4Eddy** [comment]
Hi Håkan, we are talking about Tibber Monitor. In Tibber Monitor you first need to activate the global variables with the quickapp variable setGlobalVar = true. Do you have that setting?

If setGlobalVar = true, the global variables will be created and are available in, for example, block scenes.
