### ISSUE TITLE
Breaking change in Tibber API websockets

### ISSUE THREAD

**Issue by toini** [GitHub4Eddy/tibber_live#2]
Hi!

I would like to thank you for contributing to the community of Tibber users! We've added you to the list of people we respect! https://developer.tibber.com/respect

In order to improve the API resilience we are making a breaking change for websocket communication. Please see details at [developer site](https://developer.tibber.com). Would you be able to adjust the implementation accordingly?

Also, it looks like you are not setting user-agent header value. A recommended format would be to include both the platform version and driver version for example like this: Fibaro/1.2.3 tibber_live/21'

We're trying to collect best practices [here](https://developer.tibber.com/docs/guides/calling-api)

Let us know if in need of any assistance!

Br,
Toni
Tibber

**Comment by GitHub4Eddy** [comment]
Thanks Toni, for the compliment. A lot of happy Fibaro and Tibber users build there smart solutions with the Tibber Live QuickApp and Tibber Monitor Quickapp. 

I will have a look at the API webSocket changes. It was hard to build the interface between the two platforms Fibaro and Tibber, so I hope the changes aren’t big.

I also will have a look at the user-agent header. 

Greetings Eddy

**Comment by GitHub4Eddy** [comment]
Hi Toni, some questions from the documentation.

"Support for old protocol will be removed during December 2022. Also, at the same time, the URL for connecting to websocket server changes."

"At the same time" Does that mean there is no way to adapt the changes earlier than December, test them and provide the users the new software?

In the document "Communicating with the API" under "GraphQL Subscriptions Endpoint" the new query is mentioned, but under "Subscribing to data with websockets" the old query is still mentioned? How does the new query should look like?

**Comment by toini** [comment]
1. "At the same time": No, both endpoints are operational so you can run the software for a test period and we'll remove it after we've confirmed everything works.

2. "Subscribing to data with websockets"

The query for starting the subscription and upgrading to a websocket still looks the same. For example:
```subscription{
  liveMeasurement(homeId:"96a14971-525a-4420-aae9-e5aedaa129ff") {
    timestamp
    power
    maxPower
  }
}
```

It just needs to be sent to another server. Also, after that the protocol for websocket communication has some changes.

**Comment by toini** [comment]
I tried to compile a list for changes in the websocket protocol. Here it is but im not 100% sure it covers all:

1. Subprotocol name graphql-transport-ws
2. Connection init message format structure and type (subscribe, not start)
3. Returning message type (next, not data)
4. Id must be string

**Comment by GitHub4Eddy** [comment]
Thanks, I will give it a try

**Comment by toini** [comment]
Note that the token needs to be passed as json object, not string in the connection init message.

**Comment by GitHub4Eddy** [comment]
In the current solution I also pass the header as a json object, like this:

```
  headers = {} -- Headers for authorization and protocol
  headers["Authorization"] = token
  headers["Sec-WebSocket-Protocol"] = "graphql-ws"
```

and: 

`self.sock:connect(url, headers)
`

**Comment by toini** [comment]
The thing is that the header is not passed to [graphql-ws library's](https://github.com/enisdenjo/graphql-ws)  onConnect method. See example on their readme:

```
useServer(
  {
    schema,
    onConnect: async (ctx) => {
      // do your auth check on every connect (recommended)
      if (!(await isTokenValid(ctx.connectionParams?.token)))
        // returning false from the onConnect callback will close with `4403: Forbidden`;
        // therefore, being synonymous to ctx.extra.socket.close(4403, 'Forbidden');
        return false;
    },
```

Thus, you'll need to pass it in the connection params. You can omit the Authorization header as it wont be read.

**Comment by toini** [comment]
Actually, that's not entirely correct. Headers are passed in the `ctx.extra.request.headers`. However the implementation follows the example and thus it's read from the connectionParams only.

What you should do though is add a new header for user-agent and pass that!

**Comment by toini** [comment]
We'll actually make it mandatory to pass a user-agent header when calling websockets

**Comment by GitHub4Eddy** [comment]
You don't make it easy for us with your changes ;-)

**Comment by GitHub4Eddy** [comment]
I made the changes you suggested, but it doesn't work. 

These are the changes I made:

```
url = "wss://api.tibber.com/v1-beta/gql/subscriptions" -- Tibber Live (old) webSocket URL
chenged to 
url = "wss://websocket-api.tibber.com/v1-beta/gql/subscriptions" -- Tibber Live (new) webSocket URL

headers["Sec-WebSocket-Protocol"] = "graphql-ws" -- Old Tibber header protocol
changed to 
headers["Sec-WebSocket-Protocol"] = "graphql-transport-ws" -- New Tibber header protocol

Added
headers["User-Agent"] = "Fibaro/HC3" -- New Tibber mandatory user-agent

graphql_query.type = "start" -- Old Tibber graphql_query.type
changed to
graphql_query.type = "subscribe" -- New Tibber graphql_query.type

self.sock:addEventListener("dataReceived", function(data) self:handleDataReceived(data) end) -- Old Tibber Returning message type
changed to
self.sock:addEventListener("dataReceived", function(data) self:handleDataReceived(next) end) -- New Tibber Returning message type
```

You were not sure those are all the changes. Are there any more?

**Comment by toini** [comment]
> You don't make it easy for us with your changes ;-)
We're just trying to make the API more stable... :)

> Are there any more?
Check the change number 2 above: are you passing the token as JSON value token: "value", not as string "token=value"? See https://github.com/tibber/Tibber.SDK.NET/commit/fe1d396d36c5fcc9b81ba2d7a52c10108a63d0db#diff-43fedf3288bf7eb7404444803d406886bd517a4ed366f890a641fbaec11df5a4R199

**Comment by toini** [comment]
What kind of error are you getting?

**Comment by GitHub4Eddy** [comment]
None, that makes it a bit difficult. There is just no connection, the software tries to connect for a few time, like it is coded and then stops.

**Comment by toini** [comment]
Can you tell me your ip so I can check logs?

**Comment by GitHub4Eddy** [comment]
I just let the quickapp do a run and send you a mail with some details

**Comment by toini** [comment]
Works now! Thanks @GitHub4Eddy

**Comment by GitHub4Eddy** [comment]
Thanks @toini  for your help!

Now for some finetuning and publishing is for the (Fibaro) users.

**Comment by toini** [comment]
I see one connection with user agent Fibaro/HC3 within 24 hours in the new server. What's the new user agent value? And will clients be updated automatically?

**Comment by GitHub4Eddy** [comment]
The new user-agent will look like "Tibber_Live/2.2 Fibaro/HC3 Firmware/5.130"

(or an other number for firmware, depending on their firmware version)

**Comment by GitHub4Eddy** [comment]
Users have to manually update their quickapps, so it could take some time
